
name: Lighthouse
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Lighthouse and test budgets
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://suspicious-easley-c45b61.netlify.com/
            https://suspicious-easley-c45b61.netlify.com/blog
          budgetPath: ./budget.json
          temporaryPublicStorage: true

